# ---------------------------------------------------------------
# ---------------------------------------------------------------
# 欢迎使用 Hexo-Theme-Type
# 本文件为「主题配置文件」，当在文档中看到「主题配置文件」字样时，请在本文件中进行修改。
# 本文件有严格的缩进限制，请确保在修改时，没有打乱原有的缩进
# Hexo-Theme-Type 是一个尚在开发过程中的主题，当「主题配置文件」有修改时，您可能需要重新在这里配置所有的选项。
# 当「主题配置文件」有修改时，会修改版本号的第二位数。
# 您不应当编辑这个参数
ver: 0.4.5
# ---------------------------------------------------------------
# ---------------------------------------------------------------

# ---------------------------------------------------------------
# ICON Settings 图标设置
# ---------------------------------------------------------------

favicon: 
avatar: 
apple_icon:
  # iPhone 57x57 
  iphone: 
  # iPad 72x72
  ipad: 
  # Retina iPhone 114x114
  iphone_hd: 
  # Retina iPad 144x144
  ipad_hd: 
  
# ---------------------------------------------------------------
# Style Settings 样式设置
# ---------------------------------------------------------------

# Schemes
# Use column ｜ m3
# column 样式已经不再支持
# column is out of support
schemes: m3

# Fonts
# Use LXGW ｜ 
fonts: 

# Color
color:
  main_color: '#71AFDD'
  sub_color: '#6CD9CE'
  main_black: '#222831'

# Header Links Style 导航链接样式
# 从 https://iconpark.oceanengine.com/home 获取图标包链接
# to https://iconpark.oceanengine.com/home get nav_style_src links
# Use text ｜ icon
nav_style: icon
nav_style_src: https://lf1-cdn-tos.bytegoofy.com/obj/iconpark/icons_20213_18.4a5f87dae8e6f9e336b9ad6fa00f8e8f.js

# Random Pictures
random_pic_switch: false
random_pics: 19
random_thumbnail: https://cdn.jsdelivr.net/gh/aiokr/hexo-theme-type-random_pics@v1.0.0/randompic-
# random_thumbnail: ../img/random/randompic-

# Post 
post_toc: true

# ---------------------------------------------------------------
# Header and Nav Settings 页眉、导航和封面设置
# icon list: https://fonts.google.com/icons?icon.set=Material+Icons
# 图标列表可参考: https://fonts.google.com/icons?icon.set=Material+Icons
# ---------------------------------------------------------------

# Header Cover 首页封面背景图
header: 
  img: 

# Header Links 首页导航连接
search_btn: false
nav:
  归档: 
    link: /archives/
    icon: inbox
  影像:
    link: /gallery/
    icon: gallery
  关于:
    link: /about/
    icon: person
  链接:
    link: /links/
    icon: people

# Cover Links 封面卡片底部链接
cover_links_switch: true
cover_links:
  - title: Gallery
    link: /gallery/
  - title: RSS Feed
    link: /atom.xml

# Social link 社交链接
social_link:
  # 微信二维码 显示在首页封面卡片底部
  wechat_personal: 
  # 微信个人号
    switch: false
    src: 
  wechat_public: 
  # 微信公众号
    switch: false
    src: 

# ---------------------------------------------------------------
# Footer Settings 页脚设置
# ---------------------------------------------------------------

start_time: 2016 
# 如果设置 count 选项，需要运行 npm install hexo-symbols-count-time --save
# 'count' need run 'npm install hexo-symbols-count-time --save'
count: true
icp: 

# CDN LOGO
# Use upyun | vercel | self
footer_logo: 
  use: self
  upyun: '../img/upyun.png'
  vercel: '../img/vercel-logotype-dark.svg'
  self:
    link: '../about/'
    src: 'https://imgur.lzmun.com/picgo/after2022/tripper2whitefull.png_avatar'

# ---------------------------------------------------------------
# Posts Settings 文章设置
# ---------------------------------------------------------------

# Post
default_post_title: Untitled
auto_excerpt:
  length: 120

# highlight.js 代码高亮
# style github | tomorrow | night-blue | night-bright | night-eighties
highlight:
  use: true
  style: github

# Copyright

# ---------------------------------------------------------------
# Pages Settings 独立页面设置
# ---------------------------------------------------------------

photography_page:
  slogan: true
  slogan_descr: 'The moments when I pressed the shutter, the moments are forever.'

# ---------------------------------------------------------------
# Third Party Services Settings 第三方服务设置
# ---------------------------------------------------------------

# Comment 评论
# Use cusdis ｜ waline
# disqusjs 参考 https://github.com/SukkaW/DisqusJS 进行部署
comment:
  use: waline
  cusdis:
    host:
    app_id: 
  waline:
    serverurl: https://comment.tripper.press/

# Search 搜索
# Use hexo-generator-search or hexo-algoliasearch
# if use local, use 'npm install hexo-generator-search --save' to install
# if use algolia use 'npm install hexo-algoliasearch --save' to install
search:
  #use: local
  use: algolia

# Busuanzi Count 不蒜子计数
busuanzi: false

# Google Analytics 谷歌分析
# cloudflare-workers-async-google-analytics
# if use is default, it will use analytics.js
# if use is cf_async, look at the https://github.com/SukkaW/cloudflare-workers-async-google-analytics to learn more
# if use is gtag，will use Google GA 4 id gtag.js 
# 如果 use 项选择 default，将使用 analytics.js 文件接入谷歌分析
# 如果 use 项选择 cf_async，请浏览 https://github.com/SukkaW/cloudflare-workers-async-google-analytics 进行配置
# 如果 use 项选择 gtag，将使用 Google 全局网站代码 (gtag.js) 接入谷歌分析
# Use: default | cf_async | gtag
google_analytics: 
  use: gtag
  ga_id: 
  ga_api: 
  gtag_id: G-HFH67WJVKQ

# umami Analytics
umami_analytics: 
  use: false
  id: 
  src: 

# Vercel Audiences Analytics
vercel_analytics:
  use: false

# chart.js
# https://www.chartjs.org/
chart_js:
  use: false

# ---------------------------------------------------------------
# Assets CDN Settings 资源托管设置
# ---------------------------------------------------------------

# Use jsdelivr | self_host
# 如果你的站点接入了 Cloudflare，建议您使用 self_host 选项，以便资源可以被 Cloudflare 正确缓存。
cdn:
  use: self_host

# ---------------------------------------------------------------
# Others Settings 其他功能设置
# ---------------------------------------------------------------

# PWA 尚是一个实验性功能，不建议您启用。
# 如果需要启用，需要手动创立 manifest.json 文件
# 暂时没有提供 service-worker.js 文件
pwa: 
  use: false
  theme_color: '#71afdd'

# Google 搜索增强
# 使得您的搜索结果呈现主题概览
# 开启此功能，会在页面中添加结构化数据，以便被 Google 索引
# 中文介绍：https://developers.google.com/search/docs/advanced/appearance/overview?hl=zh-cn
# English Docs: https://developers.google.com/search/docs/appearance/structured-data/search-gallery
# 这是一个实验性功能，尚未开发完成。
google_search_advanced:
# 全局开关
  use: true
# 文章页开关
  article: true